# Ativa o perfil para uso
spring.config.activate.on-profile=local

# 1. Configuração do Banco (Aponta para localhost:3307, a porta mapeada no Docker)
spring.datasource.url=jdbc:mysql://localhost:3307/product_db
spring.datasource.username=sifat_user
spring.datasource.password=sifat_pass
spring.jpa.hibernate.ddl-auto=none

# 2. Configuração do Kafka (Aponta para localhost:9092, a porta mapeada no Docker)
spring.kafka.bootstrap-servers=localhost:9092

# 3. Flyway e JPA
spring.flyway.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect